spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/housekeeper
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
#      ddl-auto: create
      naming:
        physical-strategy: com.lafin.housekeeper.repository.config.TableNamingStrategy
server:
  port: 8080
logging:
  level:
    root: debug