spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:housekeeper
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: com.lafin.housekeeper.repository.config.TableNamingStrategy
server:
  port: 8080
logging:
  level:
    root: info
jwt:
  secret: SECRET_KEY